use_frameworks!

platform :ios, '9.0'

target 'HttpEngineSwift_Example' do
  pod 'HttpEngineSwift', :path => '../'

  target 'HttpEngineSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
